const colors = {
  light: {
    text: "#0A0A0A",
    tint: "#F5A41A",
    background: "#F7F7F7",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    primary: "#0A0A0A",
    primaryForeground: "#F7F7F7",
    secondary: "#EBEBEB",
    secondaryForeground: "#1A1A1A",
    muted: "#EBEBEB",
    mutedForeground: "#737373",
    accent: "#EBEBEB",
    accentForeground: "#1A1A1A",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#D9D9D9",
    input: "#D9D9D9",
    gold: "#F5A41A",
    goldForeground: "#0A0A0A",
  },
  dark: {
    text: "#FAFAFA",
    tint: "#F5A41A",
    background: "#0A0A0A",
    foreground: "#FAFAFA",
    card: "#0F0F0F",
    cardForeground: "#FAFAFA",
    primary: "#FAFAFA",
    primaryForeground: "#0A0A0A",
    secondary: "#1F1F1F",
    secondaryForeground: "#FAFAFA",
    muted: "#1F1F1F",
    mutedForeground: "#A3A3A3",
    accent: "#1F1F1F",
    accentForeground: "#FAFAFA",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#333333",
    input: "#333333",
    gold: "#F5A41A",
    goldForeground: "#0A0A0A",
  },
  radius: 8,
};

export default colors;
