import SwiftUI
import WidgetKit
import Foundation
private let group="group.app.v1ce"
struct Snapshot:Codable{let sobrietyDate:String;let displayName:String;let coinColor:String;let coinMotto:String}
private func snap()->Snapshot?{guard let d=UserDefaults(suiteName:group)?.data(forKey:"v1ce_widget_profile_v1") else{return nil};return try? JSONDecoder().decode(Snapshot.self,from:d)}
private func days(_ s:String,_ now:Date)->Int{let f=DateFormatter();f.dateFormat="yyyy-MM-dd";f.timeZone=.current;guard let x=f.date(from:String(s.prefix(10))) else{return 0};return max(0,Calendar.current.dateComponents([.day],from:Calendar.current.startOfDay(for:x),to:Calendar.current.startOfDay(for:now)).day ?? 0)}
private func display(_ d:Int)->(Int,String){let y=d/365,m=(d%365)/30;if y>0{return(y,y==1 ? "YEAR":"YEARS")};if m>0{return(m,m==1 ? "MONTH":"MONTHS")};return(d,"DAYS")}
private func color(_ h:String)->Color{let x=h.replacingOccurrences(of:"#",with:"");guard let n=UInt64(x,radix:16),x.count==6 else{return Color(red:.96,green:.84,blue:.50)};return Color(red:Double((n>>16)&255)/255,green:Double((n>>8)&255)/255,blue:Double(n&255)/255)}
struct Entry:TimelineEntry{let date:Date;let data:Snapshot?}
struct Provider:TimelineProvider{func placeholder(in c:Context)->Entry{Entry(date:.now,data:nil)};func getSnapshot(in c:Context,completion:@escaping(Entry)->Void){completion(Entry(date:.now,data:snap()))};func getTimeline(in c:Context,completion:@escaping(Timeline<Entry>)->Void){let n=Date();let next=Calendar.current.date(byAdding:.day,value:1,to:Calendar.current.startOfDay(for:n))!;completion(Timeline(entries:[Entry(date:n,data:snap()),Entry(date:next,data:snap())],policy:.after(next)))}}
struct V1CEWidgetView:View{let entry:Entry;@Environment(\.widgetFamily)var family;var body:some View{let d=entry.data.map{days($0.sobrietyDate,entry.date)} ?? 0;let v=display(d);let bg=entry.data.map{color($0.coinColor)} ?? Color(red:.96,green:.84,blue:.50);VStack(spacing:6){Text("\(v.0)").font(.system(size:family == .systemLarge ? 44:30,weight:.bold,design:.rounded));Text(v.1).font(.system(size:10,weight:.semibold));if let n=entry.data?.displayName,!n.isEmpty{Text(n.uppercased()).font(.caption2.bold())};if family == .systemLarge,let m=entry.data?.coinMotto,!m.isEmpty{Text(m).font(.caption2).multilineTextAlignment(.center)}}.frame(maxWidth:.infinity,maxHeight:.infinity).foregroundStyle(Color.black).containerBackground(for:.widget){bg}.widgetURL(URL(string:"v1ce://home"))}}
@main struct V1CEWidget:Widget{let kind="V1CEWidget";var body:some WidgetConfiguration{StaticConfiguration(kind:kind,provider:Provider()){V1CEWidgetView(entry:$0)}.configurationDisplayName("V1CE").description("Your V1CE sobriety count.").supportedFamilies([.systemSmall,.systemMedium,.systemLarge,.accessoryCircular,.accessoryRectangular,.accessoryInline])}}