import React from "react";
import {View,Text,StyleSheet} from "react-native";
export const COIN_COLORS={
  gold:{bg:"#F5D680",border:"#0a0a0a",text:"#0a0a0a",accent:"#C4922E"},
  silver:{bg:"#E0E0E0",border:"#0a0a0a",text:"#0a0a0a",accent:"#909090"},
  bronze:{bg:"#CD7F32",border:"#0a0a0a",text:"#0a0a0a",accent:"#8B4513"},
  rose_gold:{bg:"#E8B4B8",border:"#0a0a0a",text:"#0a0a0a",accent:"#A45A68"},
  midnight:{bg:"#0a0a0a",border:"#fff",text:"#fff",accent:"#555"},
  emerald:{bg:"#2E8B57",border:"#0a0a0a",text:"#0a0a0a",accent:"#155E30"}
} as const;
export const NUMBER_STYLES={classic:{fontWeight:"700"},poppins:{fontWeight:"700"},monospace:{fontWeight:"700"},fredoka:{fontWeight:"400"},serif:{fontWeight:"700"},dmsans:{fontWeight:"700"},courier:{fontWeight:"700"},bodoni:{fontWeight:"700"},syne:{fontWeight:"700"},pacifico:{fontWeight:"400"},bebas:{fontWeight:"400"},inter:{fontWeight:"700"}} as const;
export const SHAPES=["circle","hexagon","octagon","shield","diamond","star","cross","badge","arrow"] as const;
function resolveColor(color:string){if(color in COIN_COLORS)return COIN_COLORS[color as keyof typeof COIN_COLORS];if(color?.startsWith("#")){const r=parseInt(color.slice(1,3),16),g=parseInt(color.slice(3,5),16),b=parseInt(color.slice(5,7),16),l=(.299*r+.587*g+.114*b)/255;const t=l>.5?"#0a0a0a":"#fff";return{bg:color,border:t,text:t,accent:t}}return COIN_COLORS.gold}
function shapeStyle(shape:string,size:number){if(shape==="circle")return{borderRadius:size/2};if(shape==="diamond")return{transform:[{rotate:"45deg"}],borderRadius:8};if(shape==="shield")return{borderTopLeftRadius:size*.2,borderTopRightRadius:size*.2,borderBottomLeftRadius:size*.3,borderBottomRightRadius:size*.3};if(shape==="hexagon"||shape==="octagon")return{borderRadius:18};if(shape==="star")return{borderRadius:28};return{borderRadius:14}}
export default function CoinFront({days=0,shape="circle",color="gold",numberStyle="classic",size=260,displayName,showBorder=true,coinPhoto,imageOnlyMode=false,borderColor,numberColor}:{days?:number;shape?:string;color?:string;numberStyle?:string;size?:number;displayName?:string;motto?:string;showBorder?:boolean;coinPhoto?:string;imageOnlyMode?:boolean;borderColor?:string;numberColor?:string}){const c=resolveColor(color);const years=Math.floor(days/365);const months=Math.floor(days%365/30);const main=years>=1?years:months>=1?months:days;const label=years>=1?(years===1?"YEAR":"YEARS"):months>=1?(months===1?"MONTH":"MONTHS"):"DAYS";return <View style={[s.wrap,{width:size,height:size}]}><View style={[s.coin,shapeStyle(shape,size),{width:size,height:size,backgroundColor:c.bg,borderColor:borderColor||c.border,borderWidth:showBorder?4:0,overflow:"hidden"}]}>{coinPhoto&&<View style={[StyleSheet.absoluteFill,{backgroundColor:c.bg,opacity:imageOnlyMode?1:.35}]}/>} {!imageOnlyMode&&<View style={s.content}><Text style={[s.number,{color:numberColor||c.text,fontSize:size*.32}]}>{main}</Text><Text style={[s.label,{color:numberColor||c.text,fontSize:size*.09}]}> {label}</Text>{displayName&&<Text style={[s.name,{color:numberColor||c.text,fontSize:size*.04}]}>{displayName.toUpperCase()}</Text>}{motto&&<Text style={[s.name,{color:numberColor||c.text,fontSize:size*.035}]}>{motto}</Text>}</View>}</View></View>}
const s=StyleSheet.create({wrap:{alignItems:"center",justifyContent:"center"},coin:{alignItems:"center",justifyContent:"center"},content:{alignItems:"center",justifyContent:"center"},number:{fontWeight:"700",lineHeight:Math.round(260*.29)},label:{fontWeight:"700",letterSpacing:3,opacity:.7},name:{fontWeight:"500",letterSpacing:2,opacity:.4,marginTop:8}});
