import React,{useEffect,useState} from "react";
import {Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from "react-native";
import {useAuth} from "@/context/AuthContext";
import {supabase} from "@/lib/supabase";
import {useColors} from "@/hooks/useColors";
type Friend={id:string;requester_email:string;addressee_email:string;status:string;is_active:boolean};
export default function Friends(){const{user}=useAuth();const c=useColors();const[email,setEmail]=useState("");const[friends,setFriends]=useState<Friend[]>([]);const[pending,setPending]=useState<Friend[]>([]);const[blocked,setBlocked]=useState<any[]>([]);
const load=async()=>{if(!user?.email)return;const e=user.email;const a=await supabase.from("FriendConnection").select("*").or("requester_email.eq."+e+",addressee_email.eq."+e).eq("is_active",true);const b=await supabase.from("FriendConnection").select("*").eq("addressee_email",e).eq("status","pending");const d=await supabase.from("BlockedUser").select("*").eq("blocker_email",e);setFriends((a.data||[]) as Friend[]);setPending((b.data||[]) as Friend[]);setBlocked(d.data||[])};
useEffect(()=>{load()},[user?.email]);
const send=async()=>{if(!user?.email||!email.trim())return;const target=email.trim().toLowerCase();if(target===user.email.toLowerCase())return Alert.alert("V1CE","You can't add yourself.");const{error}=await supabase.from("FriendConnection").insert({requester_email:user.email,addressee_email:target,status:"pending",is_active:false});if(error)Alert.alert("V1CE",error.message);else{setEmail("");Alert.alert("V1CE","Friend request sent!");load()}};
const action=async(id:string,status:string,is_active:boolean)=>{const{error}=await supabase.from("FriendConnection").update({status,is_active}).eq("id",id);if(error)Alert.alert("V1CE",error.message);load()};
const remove=async(id:string)=>{await supabase.from("FriendConnection").update({is_active:false}).eq("id",id);load()};
return <ScrollView style={{backgroundColor:c.background}} contentContainerStyle={s.container}><Text style={[s.title,{color:c.foreground}]}>FRIENDS.</Text><Text style={{color:c.mutedForeground}}>Connect with people on their sobriety journey.</Text><View style={s.row}><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Enter email" placeholderTextColor={c.mutedForeground} style={[s.input,{borderColor:c.foreground,color:c.foreground}]}/><TouchableOpacity onPress={send} style={[s.send,{backgroundColor:c.foreground}]}><Text style={{color:c.background,fontWeight:"800"}}>SEND</Text></TouchableOpacity></View><Text style={[s.heading,{color:c.foreground}]}>YOUR FRIENDS</Text>{friends.length===0?<Text style={{color:c.mutedForeground}}>No friends yet.</Text>:friends.map(f=><View key={f.id} style={[s.card,{borderColor:c.border}]}><Text style={{color:c.foreground,fontWeight:"700"}}>{f.requester_email===user?.email?f.addressee_email:f.requester_email}</Text><TouchableOpacity onPress={()=>remove(f.id)}><Text style={{color:c.mutedForeground}}>REMOVE</Text></TouchableOpacity></View>)}<Text style={[s.heading,{color:c.foreground}]}>PENDING REQUESTS</Text>{pending.length===0?<Text style={{color:c.mutedForeground}}>No pending requests</Text>:pending.map(f=><View key={f.id} style={[s.card,{borderColor:c.border}]}><Text style={{color:c.foreground}}>{f.requester_email}</Text><View style={s.actions}><TouchableOpacity onPress={()=>action(f.id,"accepted",true)}><Text style={{color:c.foreground,fontWeight:"800"}}>ACCEPT</Text></TouchableOpacity><TouchableOpacity onPress={()=>action(f.id,"rejected",false)}><Text style={{color:c.mutedForeground}}>REJECT</Text></TouchableOpacity></View></View>)}<Text style={[s.heading,{color:c.foreground}]}>BLOCKED USERS</Text>{blocked.length===0?<Text style={{color:c.mutedForeground}}>No blocked users</Text>:blocked.map((b:any)=><View key={b.id} style={[s.card,{borderColor:c.border}]}><Text style={{color:c.foreground}}>{b.blocked_email}</Text><TouchableOpacity onPress={async()=>{await supabase.from("BlockedUser").delete().eq("id",b.id);load()}}><Text style={{color:c.mutedForeground}}>UNBLOCK</Text></TouchableOpacity></View>)}</ScrollView>}
const s=StyleSheet.create({container:{padding:20,paddingTop:55,paddingBottom:60},title:{fontSize:48,fontWeight:"900"},row:{flexDirection:"row",gap:8,marginTop:28},input:{flex:1,borderWidth:2,padding:12,fontSize:14},send:{paddingHorizontal:18,justifyContent:"center"},heading:{fontSize:22,fontWeight:"900",letterSpacing:2,marginTop:34,marginBottom:12},card:{borderWidth:2,padding:16,marginBottom:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},actions:{flexDirection:"row",gap:18}});