import React,{useEffect,useMemo,useState} from "react";
import {ScrollView,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import {useRouter} from "expo-router";
import {useAuth} from "@/context/AuthContext";
import {useColors} from "@/hooks/useColors";
import CoinFront from "@/components/CoinFront";
const WORDS=["SOBER","UNBOTHERED","HYDRATED","EMPLOYABLE","ASCENDING","CRAZY","SLAYING","FEELING","EXPERIENCING","SHOWING UP","CAFFEINATED","UNHINGED","VALID","VIBING","GRATEFUL","GAY","PROUD","CLEAN","HAPPY","RICH","LOVED"];
function elapsed(start:string){const ms=Math.max(0,Date.now()-new Date(start+"T00:00:00").getTime());return{days:Math.floor(ms/86400000),hours:Math.floor(ms/3600000)%24,minutes:Math.floor(ms/60000)%60,seconds:Math.floor(ms/1000)%60}}
export default function Home(){const{profile}=useAuth();const c=useColors();const router=useRouter();const[now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const time=useMemo(()=>profile?elapsed(profile.sobriety_date):{days:0,hours:0,minutes:0,seconds:0},[profile,now]);return <ScrollView style={{backgroundColor:c.background}} contentContainerStyle={s.container}><View style={s.header}><Text style={[s.kicker,{color:c.mutedForeground}]}>YOUR</Text><Text style={[s.title,{color:c.foreground}]}>JOURNEY.</Text></View><View style={s.word}><Text style={[s.wordText,{color:c.foreground}]}>{WORDS[Math.floor(now/1500)%WORDS.length]}</Text></View><View style={[s.coinWrap,{borderColor:c.foreground}]}>{profile?<CoinFront days={time.days} shape={profile.coin_shape||"circle"} color={profile.coin_color||"#F5D680"} numberStyle={profile.number_style||"classic"} displayName={profile.display_name} motto={profile.coin_motto} showBorder={profile.coin_show_border!==false} borderColor={profile.coin_border_color} numberColor={profile.coin_number_color} coinPhoto={profile.coin_photo} imageOnlyMode={profile.coin_image_only} size={230}/>:<Text style={{color:c.mutedForeground}}>Set your sobriety date to start tracking.</Text>}</View><View style={s.elapsed}><Text style={[s.section,{color:c.foreground}]}>TIME ELAPSED</Text><View style={s.grid}>{[[time.days,"DAYS"],[time.hours,"HRS"],[time.minutes,"MIN"],[time.seconds,"SEC"]].map(([v,l])=><View key={String(l)}><Text style={[s.num,{color:c.foreground}]}>{String(v).padStart(2,"0")}</Text><Text style={[s.small,{color:c.mutedForeground}]}>{l}</Text></View>)}</View></View><TouchableOpacity onPress={()=>router.push("/(tabs)/customize")} style={[s.button,{backgroundColor:c.foreground}]}><Text style={{color:c.background,fontWeight:"800"}}>CUSTOMIZE →</Text></TouchableOpacity></ScrollView>}
const s=StyleSheet.create({container:{padding:20,paddingBottom:50},header:{borderBottomWidth:2,paddingTop:24,paddingBottom:18},kicker:{fontSize:12,letterSpacing:5,fontWeight:"700"},title:{fontSize:52,fontWeight:"900",lineHeight:52},word:{paddingVertical:18},wordText:{fontSize:14,fontWeight:"800",letterSpacing:4},coinWrap:{alignItems:"center",justifyContent:"center",paddingVertical:25,borderBottomWidth:2},elapsed:{paddingVertical:24},section:{fontSize:22,fontWeight:"900",letterSpacing:2},grid:{flexDirection:"row",justifyContent:"space-between",marginTop:18},num:{fontSize:32,fontWeight:"800"},small:{fontSize:9,letterSpacing:2,fontWeight:"700",marginTop:3},button:{height:54,alignItems:"center",justifyContent:"center",marginTop:5}});