import React,{useEffect,useRef,useState} from "react";
import {StyleSheet,Text,TouchableOpacity,View} from "react-native";
const COLS=20,ROWS=24,CELL=14;
type P={x:number;y:number};type Dir={x:number;y:number};
const DIRS={UP:{x:0,y:-1},DOWN:{x:0,y:1},LEFT:{x:-1,y:0},RIGHT:{x:1,y:0}};
function rand(n:number){return Math.floor(Math.random()*n)} function free(s:P[]){let p:P;do{p={x:rand(COLS),y:rand(ROWS)}}while(s.some(x=>x.x===p.x&&x.y===p.y));return p}
function init(){const snake=[{x:10,y:12},{x:9,y:12},{x:8,y:12}];return{snake,food:free(snake),score:0,dead:false}}
export default function SnakeGame(){const[state,setState]=useState(init);const[started,setStarted]=useState(false);const dir=useRef<Dir>(DIRS.RIGHT);
useEffect(()=>{if(!started)return;const id=setInterval(()=>setState(prev=>{if(prev.dead)return prev;const h=prev.snake[0];const n={x:h.x+dir.current.x,y:h.y+dir.current.y};if(n.x<0||n.x>=COLS||n.y<0||n.y>=ROWS||prev.snake.some(p=>p.x===n.x&&p.y===n.y))return{...prev,dead:true};const ate=n.x===prev.food.x&&n.y===prev.food.y;const snake=[n,...prev.snake];if(!ate)snake.pop();return{...prev,snake,food:ate?free(snake):prev.food,score:prev.score+(ate?1:0)}}),160);return()=>clearInterval(id)},[started]);
const change=(d:Dir)=>{if(d.x===-dir.current.x&&d.y===-dir.current.y)return;dir.current=d;if(!started)setStarted(true)};
return <View style={s.wrap}><View style={s.board}>{state.snake.map((p,i)=><View key={i} style={[s.cell,{left:p.x*CELL,top:p.y*CELL,backgroundColor:i?"#333":"#0a0a0a"}]}/>) }<Text style={[s.food,{left:state.food.x*CELL,top:state.food.y*CELL}]}>$</Text>{!started&&!state.dead&&<View style={s.overlay}><Text style={s.overlayTitle}>JAYWALKER</Text><TouchableOpacity onPress={()=>setStarted(true)} style={s.button}><Text style={s.buttonText}>START →</Text></TouchableOpacity></View>}{state.dead&&<View style={s.overlay}><Text style={s.overlayTitle}>GAME OVER</Text><Text>Score: {state.score}</Text><TouchableOpacity onPress={()=>{dir.current=DIRS.RIGHT;setState(init());setStarted(false)}} style={s.button}><Text style={s.buttonText}>RETRY →</Text></TouchableOpacity></View>}</View><Text style={s.score}>SCORE {state.score}</Text><View style={s.controls}><TouchableOpacity onPress={()=>change(DIRS.LEFT)} style={s.control}><Text>←</Text></TouchableOpacity><View><TouchableOpacity onPress={()=>change(DIRS.UP)} style={s.control}><Text>↑</Text></TouchableOpacity><TouchableOpacity onPress={()=>change(DIRS.DOWN)} style={s.control}><Text>↓</Text></TouchableOpacity></View><TouchableOpacity onPress={()=>change(DIRS.RIGHT)} style={s.control}><Text>→</Text></TouchableOpacity></View></View>}
const s=StyleSheet.create({wrap:{alignItems:"center",paddingVertical:10},board:{width:COLS*CELL,height:ROWS*CELL,borderWidth:2,borderColor:"#0a0a0a",backgroundColor:"#fff",position:"relative"},cell:{position:"absolute",width:CELL,height:CELL},food:{position:"absolute",fontSize:13,fontWeight:"900",width:CELL,height:CELL,textAlign:"center"},overlay:{position:"absolute",inset:0,backgroundColor:"rgba(255,255,255,.92)",alignItems:"center",justifyContent:"center",gap:10},overlayTitle:{fontSize:24,fontWeight:"900"},button:{backgroundColor:"#0a0a0a",paddingHorizontal:20,paddingVertical:10},buttonText:{color:"#fff",fontWeight:"900"},score:{fontWeight:"800",letterSpacing:2,marginTop:10},controls:{flexDirection:"row",alignItems:"center",gap:10,marginTop:12},control:{width:44,height:36,borderWidth:2,borderColor:"#0a0a0a",alignItems:"center",justifyContent:"center",marginVertical:2}});